### ISSUE TITLE
main language?

### ISSUE THREAD

**Issue by iandoug** [christoofar/canaria#1]
Hi

My layout naming scheme did not think far enough ahead to handle multilingual boards...

So now, would you prefer canaria.en.ansi or canaria.es.ansi ?

Going canaria.en-es.ansi will get klunky when there are 3 or more languages ... it also will require rethinking parts of database, programs, etc ...

Thanks, Ian

**Comment by christoofar** [comment]
Hi.   The layout is only proven to optimize EN and ES.
