### ISSUE TITLE
Vim key bindings

### ISSUE THREAD

**Issue by axgfn** [christoofar/canaria#2]
While I try out Canaria, I made Vim-like key bindings for:

- [vim](https://gitlab.com/ajgrf/dotfiles/-/commit/09408dd47cc1e41970ef930566b426e77090deee)
- [less](https://gitlab.com/ajgrf/dotfiles/-/commit/3a1dbc8a21bb76489dcb7381f9d22abe532f2433)
- [xmonad](https://gitlab.com/ajgrf/dotfiles/-/commit/9bb17c33541421545c7a4eb983bd1c25c814f871)
- [tridactyl](https://gitlab.com/ajgrf/dotfiles/-/commit/d51a4d43867a6a3c3073fb351c4a8c2ba2b993f3)
- [tmux](https://gitlab.com/ajgrf/dotfiles/-/commit/7f3e081b2e270b3d32e5608a004cb60206fa17f3)
- [emacs](https://gitlab.com/ajgrf/dotfiles/-/commit/5b9c1dfe8c843eb9163870971f3be23f97aeb9b3) (evil)

I don't plan on maintaining any of this outside of my own dotfiles, but I thought I'd share them for anyone interested. My dotfiles were already set up to support both qwerty and colemak-dh, which made this much quicker and easier than it would have otherwise been. Bindings are chosen based on the presence or absence of the `$CANARY` environment variable. (I didn't name it `$CANARIA` because the bindings work just as well in either layout.)

**Comment by christoofar** [comment]
hi @ajgrf do you want to PR them into this repo?  You are more than welcome to!

**Comment by christoofar** [comment]
I will add a section to README.md and put your links in

**Comment by christoofar** [comment]
Merged!

**Comment by oviedorodolfo** [comment]
In an ISO keyboard, would you use the key to the left of the ‘z’ for the Spanish accent and the ~ or the ñ?

**Comment by christoofar** [comment]
> In an ISO keyboard, would you use the key to the left of the ‘z’ for the Spanish accent and the ~ or the ñ?

I've thought about where that might be useful but given its frequency I wasn't sure that putting it there would be optimal, but the dead key could go there instead of where it's placed in the ANSI version.   Do you think that would be ergonomic?

**Comment by oviedorodolfo** [comment]
I think so because it will be much closer. Hitting it with your pinky will be natural if you hit the z with the ring finger.
